# Generated by Django 6.0 on 2025-12-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered')], default='sent', max_length=20),
        ),
    ]
