# Generated by Django 6.0 on 2025-12-19 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_friendship_blocked_by_userprofile_nickname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='ringtone',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='ping',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='pings/audio/'),
        ),
        migrations.AddField(
            model_name='ping',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CheckInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('safe', 'Safe'), ('alerted', 'Alerted')], default='active', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message to send if timer expires')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
